from collections.abc import Callable, Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class Angles:
    def __init__(self, arg0: float, arg1: float, /) -> None: ...

    @property
    def azimuth(self) -> float: ...

    @property
    def elevation(self) -> float: ...

    def to_direction(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @staticmethod
    def from_direction(arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Angles: ...

class MPMRK4RealisticEnvironmentRealisticProjectile:
    def __init__(self) -> None: ...

    @property
    def integrator(self) -> RK4: ...

    @integrator.setter
    def integrator(self, arg: RK4, /) -> None: ...

    @property
    def environment(self) -> RealisticEnvironment: ...

    @environment.setter
    def environment(self, arg: RealisticEnvironment, /) -> None: ...

    @property
    def projectile(self) -> RealisticProjectile: ...

    @projectile.setter
    def projectile(self, arg: RealisticProjectile, /) -> None: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    @overload
    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    def optimize_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def optimize_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Angles: ...

    def solve_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] | None: ...

    def solve_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Angles | None: ...

    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Angles, float] | None: ...

class MPMRKDP5RealisticEnvironmentRealisticProjectile:
    def __init__(self) -> None: ...

    @property
    def integrator(self) -> RKDP5: ...

    @integrator.setter
    def integrator(self, arg: RKDP5, /) -> None: ...

    @property
    def environment(self) -> RealisticEnvironment: ...

    @environment.setter
    def environment(self, arg: RealisticEnvironment, /) -> None: ...

    @property
    def projectile(self) -> RealisticProjectile: ...

    @projectile.setter
    def projectile(self, arg: RealisticProjectile, /) -> None: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    @overload
    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    def optimize_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def optimize_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Angles: ...

    def solve_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] | None: ...

    def solve_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Angles | None: ...

    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Angles, float] | None: ...

class RK4:
    def __init__(self) -> None: ...

    def set_step(self, arg: float, /) -> RK4: ...

    def step(self) -> float: ...

class RKDP5:
    def __init__(self) -> None: ...

    def set_absolute_tolerance(self, arg: float, /) -> RKDP5: ...

    def absolute_tolerance(self) -> float: ...

    def set_relative_tolerance(self, arg: float, /) -> RKDP5: ...

    def relative_tolerance(self) -> float: ...

    def set_max_step(self, arg: float, /) -> RKDP5: ...

    def max_step(self) -> float: ...

    def set_first_step(self, arg: float, /) -> RKDP5: ...

    def first_step(self) -> float: ...

class RealisticEnvironment:
    def __init__(self) -> None: ...

    def set_adiabatic_index(self, arg: float, /) -> RealisticEnvironment: ...

    def adiabatic_index(self) -> float: ...

    def set_specific_gas_constant(self, arg: float, /) -> RealisticEnvironment: ...

    def specific_gas_constant(self) -> float: ...

    @overload
    def set_temperature(self, arg: float, /) -> RealisticEnvironment: ...

    @overload
    def set_temperature(self, arg: Callable[[float], float], /) -> RealisticEnvironment: ...

    @overload
    def set_temperature(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], /) -> RealisticEnvironment: ...

    @overload
    def set_temperature(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticEnvironment: ...

    @overload
    def set_temperature(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], arg1: float, /) -> RealisticEnvironment: ...

    def temperature(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> float: ...

    @overload
    def set_pressure(self, arg: float, /) -> RealisticEnvironment: ...

    @overload
    def set_pressure(self, arg: Callable[[float], float], /) -> RealisticEnvironment: ...

    @overload
    def set_pressure(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], /) -> RealisticEnvironment: ...

    @overload
    def set_pressure(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticEnvironment: ...

    @overload
    def set_pressure(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], arg1: float, /) -> RealisticEnvironment: ...

    def pressure(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> float: ...

    @overload
    def set_gravity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> RealisticEnvironment: ...

    @overload
    def set_gravity(self, arg: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> RealisticEnvironment: ...

    @overload
    def set_gravity(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> RealisticEnvironment: ...

    @overload
    def set_gravity(self, arg0: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> RealisticEnvironment: ...

    @overload
    def set_gravity(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> RealisticEnvironment: ...

    def gravity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def set_wind_velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> RealisticEnvironment: ...

    @overload
    def set_wind_velocity(self, arg: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> RealisticEnvironment: ...

    @overload
    def set_wind_velocity(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> RealisticEnvironment: ...

    @overload
    def set_wind_velocity(self, arg0: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> RealisticEnvironment: ...

    @overload
    def set_wind_velocity(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> RealisticEnvironment: ...

    def wind_velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

class RealisticProjectile:
    def __init__(self) -> None: ...

    def set_mass(self, arg: float, /) -> RealisticProjectile: ...

    def mass(self) -> float: ...

    def set_diameter(self, arg: float, /) -> RealisticProjectile: ...

    def diameter(self) -> float: ...

    def set_reference_area(self, arg: float, /) -> RealisticProjectile: ...

    def reference_area(self) -> float: ...

    def set_axial_moment_of_inertia(self, arg: float, /) -> RealisticProjectile: ...

    def axial_moment_of_inertia(self) -> float: ...

    @overload
    def set_drag_force_coefficient(self, arg: float, /) -> RealisticProjectile: ...

    @overload
    def set_drag_force_coefficient(self, arg: Callable[[float], float], /) -> RealisticProjectile: ...

    @overload
    def set_drag_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticProjectile: ...

    @overload
    def set_drag_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> RealisticProjectile: ...

    def drag_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_lift_force_coefficient(self, arg: float, /) -> RealisticProjectile: ...

    @overload
    def set_lift_force_coefficient(self, arg: Callable[[float], float], /) -> RealisticProjectile: ...

    @overload
    def set_lift_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticProjectile: ...

    @overload
    def set_lift_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> RealisticProjectile: ...

    def lift_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_overturning_moment_coefficient(self, arg: float, /) -> RealisticProjectile: ...

    @overload
    def set_overturning_moment_coefficient(self, arg: Callable[[float], float], /) -> RealisticProjectile: ...

    @overload
    def set_overturning_moment_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticProjectile: ...

    @overload
    def set_overturning_moment_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> RealisticProjectile: ...

    def overturning_moment_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg: float, /) -> RealisticProjectile: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg: Callable[[float], float], /) -> RealisticProjectile: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticProjectile: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> RealisticProjectile: ...

    def spin_damping_moment_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_magnus_force_coefficient(self, arg: float, /) -> RealisticProjectile: ...

    @overload
    def set_magnus_force_coefficient(self, arg: Callable[[float], float], /) -> RealisticProjectile: ...

    @overload
    def set_magnus_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> RealisticProjectile: ...

    @overload
    def set_magnus_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> RealisticProjectile: ...

    def magnus_force_coefficient(self, arg: float, /) -> float: ...
