from collections.abc import Callable, Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class Angles:
    def __init__(self, azimuth: float, elevation: float) -> None: ...

    @property
    def azimuth(self) -> float: ...

    @property
    def elevation(self) -> float: ...

    def to_direction(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @staticmethod
    def from_direction(arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Angles: ...

class MPMRK4:
    def __init__(self) -> None: ...

    @property
    def integrator(self) -> RK4: ...

    @integrator.setter
    def integrator(self, arg: RK4, /) -> None: ...

    @property
    def environment(self) -> Environment: ...

    @environment.setter
    def environment(self, arg: Environment, /) -> None: ...

    @property
    def projectile(self) -> Projectile: ...

    @projectile.setter
    def projectile(self, arg: Projectile, /) -> None: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    def optimize_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, /) -> float: ...

    def optimize_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def optimize_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Angles: ...

    def solve_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] | None: ...

    def solve_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Angles | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Angles, float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Angles, float] | None: ...

class MPMRK45:
    def __init__(self) -> None: ...

    @property
    def integrator(self) -> RK45: ...

    @integrator.setter
    def integrator(self, arg: RK45, /) -> None: ...

    @property
    def environment(self) -> Environment: ...

    @environment.setter
    def environment(self, arg: Environment, /) -> None: ...

    @property
    def projectile(self) -> Projectile: ...

    @projectile.setter
    def projectile(self, arg: Projectile, /) -> None: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    def optimize_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, /) -> float: ...

    def optimize_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def optimize_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Angles: ...

    def solve_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] | None: ...

    def solve_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, /) -> Angles | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Angles, float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: int, arg10: int, /) -> tuple[Angles, float] | None: ...

class PMRK4:
    def __init__(self) -> None: ...

    @property
    def integrator(self) -> RK4: ...

    @integrator.setter
    def integrator(self, arg: RK4, /) -> None: ...

    @property
    def environment(self) -> Environment: ...

    @environment.setter
    def environment(self, arg: Environment, /) -> None: ...

    @property
    def projectile(self) -> Projectile: ...

    @projectile.setter
    def projectile(self, arg: Projectile, /) -> None: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    def optimize_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg4: float, arg5: float, arg6: float, arg7: int, /) -> float: ...

    def optimize_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def optimize_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: int, /) -> Angles: ...

    def solve_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] | None: ...

    def solve_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Angles | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Angles, float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Angles, float] | None: ...

class PMRK45:
    def __init__(self) -> None: ...

    @property
    def integrator(self) -> RK45: ...

    @integrator.setter
    def integrator(self, arg: RK45, /) -> None: ...

    @property
    def environment(self) -> Environment: ...

    @environment.setter
    def environment(self, arg: Environment, /) -> None: ...

    @property
    def projectile(self) -> Projectile: ...

    @projectile.setter
    def projectile(self, arg: Projectile, /) -> None: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def compute_final_position(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Angles, arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def compute_trajectory(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, /) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    def optimize_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg4: float, arg5: float, arg6: float, arg7: int, /) -> float: ...

    def optimize_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def optimize_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: int, /) -> Angles: ...

    def solve_launch_direction(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] | None: ...

    def solve_launch_angles(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: int, /) -> Angles | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_direction_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Angles, float] | None: ...

    @overload
    def solve_launch_angles_and_time_of_flight(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: int, arg9: int, /) -> tuple[Angles, float] | None: ...

class RK4:
    def __init__(self) -> None: ...

    def set_step(self, arg: float, /) -> RK4: ...

    def step(self) -> float: ...

class RK45:
    def __init__(self) -> None: ...

    def set_absolute_tolerance(self, arg: float, /) -> RK45: ...

    def absolute_tolerance(self) -> float: ...

    def set_relative_tolerance(self, arg: float, /) -> RK45: ...

    def relative_tolerance(self) -> float: ...

    def set_max_step(self, arg: float, /) -> RK45: ...

    def max_step(self) -> float: ...

    def set_first_step(self, arg: float, /) -> RK45: ...

    def first_step(self) -> float: ...

class Environment:
    def __init__(self) -> None: ...

    def set_adiabatic_index(self, arg: float, /) -> Environment: ...

    def adiabatic_index(self) -> float: ...

    def set_specific_gas_constant(self, arg: float, /) -> Environment: ...

    def specific_gas_constant(self) -> float: ...

    @overload
    def set_temperature(self, arg: float, /) -> Environment: ...

    @overload
    def set_temperature(self, arg: Callable[[float], float], /) -> Environment: ...

    @overload
    def set_temperature(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], /) -> Environment: ...

    @overload
    def set_temperature(self, arg0: Callable[[float], float], arg1: float, /) -> Environment: ...

    @overload
    def set_temperature(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], arg1: float, /) -> Environment: ...

    def temperature(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> float: ...

    @overload
    def set_pressure(self, arg: float, /) -> Environment: ...

    @overload
    def set_pressure(self, arg: Callable[[float], float], /) -> Environment: ...

    @overload
    def set_pressure(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], /) -> Environment: ...

    @overload
    def set_pressure(self, arg0: Callable[[float], float], arg1: float, /) -> Environment: ...

    @overload
    def set_pressure(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], float], arg1: float, /) -> Environment: ...

    def pressure(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> float: ...

    @overload
    def set_gravity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Environment: ...

    @overload
    def set_gravity(self, arg: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> Environment: ...

    @overload
    def set_gravity(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> Environment: ...

    @overload
    def set_gravity(self, arg0: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> Environment: ...

    @overload
    def set_gravity(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> Environment: ...

    def gravity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @overload
    def set_wind_velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Environment: ...

    @overload
    def set_wind_velocity(self, arg: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> Environment: ...

    @overload
    def set_wind_velocity(self, arg: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> Environment: ...

    @overload
    def set_wind_velocity(self, arg0: Callable[[float], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> Environment: ...

    @overload
    def set_wind_velocity(self, arg0: Callable[[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], arg1: float, /) -> Environment: ...

    def wind_velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @staticmethod
    def isa() -> Environment: ...

class Projectile:
    def __init__(self) -> None: ...

    def set_mass(self, arg: float, /) -> Projectile: ...

    def mass(self) -> float: ...

    def set_diameter(self, arg: float, /) -> Projectile: ...

    def diameter(self) -> float: ...

    def set_axial_moment_of_inertia(self, arg: float, /) -> Projectile: ...

    def axial_moment_of_inertia(self) -> float: ...

    def set_form_factor(self, arg: float, /) -> Projectile: ...

    def form_factor(self) -> float: ...

    def set_drag_factor(self, arg: float, /) -> Projectile: ...

    def drag_factor(self) -> float: ...

    def set_lift_factor(self, arg: float, /) -> Projectile: ...

    def lift_factor(self) -> float: ...

    def set_yaw_drag_factor(self, arg: float, /) -> Projectile: ...

    def yaw_drag_factor(self) -> float: ...

    def set_magnus_force_factor(self, arg: float, /) -> Projectile: ...

    def magnus_force_factor(self) -> float: ...

    @overload
    def set_drag_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_drag_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_drag_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_drag_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def drag_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_quadratic_yaw_drag_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_quadratic_yaw_drag_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_quadratic_yaw_drag_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_quadratic_yaw_drag_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def quadratic_yaw_drag_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_quartic_yaw_drag_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_quartic_yaw_drag_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_quartic_yaw_drag_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_quartic_yaw_drag_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def quartic_yaw_drag_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_lift_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_lift_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_lift_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_lift_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def lift_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_cubic_lift_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_cubic_lift_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_cubic_lift_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_cubic_lift_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def cubic_lift_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_quintic_lift_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_quintic_lift_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_quintic_lift_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_quintic_lift_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def quintic_lift_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_magnus_force_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_magnus_force_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_magnus_force_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_magnus_force_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def magnus_force_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_overturning_moment_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_overturning_moment_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_overturning_moment_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_overturning_moment_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def overturning_moment_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_cubic_overturning_moment_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_cubic_overturning_moment_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_cubic_overturning_moment_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_cubic_overturning_moment_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def cubic_overturning_moment_coefficient(self, arg: float, /) -> float: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg: float, /) -> Projectile: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg: Callable[[float], float], /) -> Projectile: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg0: Callable[[float], float], arg1: float, /) -> Projectile: ...

    @overload
    def set_spin_damping_moment_coefficient(self, arg0: Sequence[float], arg1: Sequence[float], /) -> Projectile: ...

    def spin_damping_moment_coefficient(self, arg: float, /) -> float: ...
